/**
 * Generated by Scrooge
 *   version: 3.14.1
 *   rev: a996c1128a032845c508102d62e65fc0aa7a5f41
 *   built at: 20140501-114733
 */
package com.am.ds.raft.rpc.thrift

import com.twitter.scrooge.{
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object GetMembersResponseST extends ThriftStructCodec3[GetMembersResponseST] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("GetMembersResponseST")
  val SuccessField = new TField("success", TType.BOOL, 1)
  val SuccessFieldManifest = implicitly[Manifest[Boolean]]
  val MembersField = new TField("members", TType.LIST, 2)
  val MembersFieldManifest = implicitly[Manifest[Seq[String]]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      SuccessField,
      false,
      SuccessFieldManifest,
      None,
      None,
      immutable$Map(
      ),
      immutable$Map(
      )
    ),
    new ThriftStructFieldInfo(
      MembersField,
      false,
      MembersFieldManifest,
      None,
      Some(implicitly[Manifest[String]]),
      immutable$Map(
      ),
      immutable$Map(
      )
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map[String, String](
    )

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: GetMembersResponseST) {
    if (_item.members == null) throw new TProtocolException("Required field members cannot be null")
  }

  override def encode(_item: GetMembersResponseST, _oproto: TProtocol) {
    _item.write(_oproto)
  }

  override def decode(_iprot: TProtocol): GetMembersResponseST = {
    var success: Boolean = false
    var _got_success = false
    var members: Seq[String] = Seq[String]()
    var _got_members = false
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.BOOL => {
                success = readSuccessValue(_iprot)
                _got_success = true
              }
              case _actualType =>
                val _expectedType = TType.BOOL
            
                throw new TProtocolException(
                  "Received wrong type for field 'success' (expected=%s, actual=%s).".format(
                    ttypeToHuman(_expectedType),
                    ttypeToHuman(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.LIST => {
                members = readMembersValue(_iprot)
                _got_members = true
              }
              case _actualType =>
                val _expectedType = TType.LIST
            
                throw new TProtocolException(
                  "Received wrong type for field 'members' (expected=%s, actual=%s).".format(
                    ttypeToHuman(_expectedType),
                    ttypeToHuman(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_success) throw new TProtocolException("Required field 'GetMembersResponseST' was not found in serialized data for struct GetMembersResponseST")
    if (!_got_members) throw new TProtocolException("Required field 'GetMembersResponseST' was not found in serialized data for struct GetMembersResponseST")
    new Immutable(
      success,
      members,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    success: Boolean,
    members: Seq[String] = Seq[String]()
  ): GetMembersResponseST =
    new Immutable(
      success,
      members
    )

  def unapply(_item: GetMembersResponseST): Option[scala.Product2[Boolean, Seq[String]]] = Some(_item)


  private def readSuccessValue(_iprot: TProtocol): Boolean = {
    _iprot.readBool()
  }

  private def writeSuccessField(success_item: Boolean, _oprot: TProtocol) {
    _oprot.writeFieldBegin(SuccessField)
    writeSuccessValue(success_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeSuccessValue(success_item: Boolean, _oprot: TProtocol) {
    _oprot.writeBool(success_item)
  }

  private def readMembersValue(_iprot: TProtocol): Seq[String] = {
    val _list = _iprot.readListBegin()
    if (_list.size == 0) {
      _iprot.readListEnd()
      Nil
    } else {
      val _rv = new mutable$ArrayBuffer[String](_list.size)
      var _i = 0
      while (_i < _list.size) {
        _rv += {
            _iprot.readString()
  
        }
        _i += 1
      }
      _iprot.readListEnd()
      _rv
    }
  }

  private def writeMembersField(members_item: Seq[String], _oprot: TProtocol) {
    _oprot.writeFieldBegin(MembersField)
    writeMembersValue(members_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeMembersValue(members_item: Seq[String], _oprot: TProtocol) {
    _oprot.writeListBegin(new TList(TType.STRING, members_item.size))
    members_item.foreach { members_item_element =>
      _oprot.writeString(members_item_element)
    }
    _oprot.writeListEnd()
  }



  private def ttypeToHuman(byte: Byte) = {
    // from https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/protocol/TType.java
    byte match {
      case TType.STOP   => "STOP"
      case TType.VOID   => "VOID"
      case TType.BOOL   => "BOOL"
      case TType.BYTE   => "BYTE"
      case TType.DOUBLE => "DOUBLE"
      case TType.I16    => "I16"
      case TType.I32    => "I32"
      case TType.I64    => "I64"
      case TType.STRING => "STRING"
      case TType.STRUCT => "STRUCT"
      case TType.MAP    => "MAP"
      case TType.SET    => "SET"
      case TType.LIST   => "LIST"
      case TType.ENUM   => "ENUM"
      case _            => "UNKNOWN"
    }
  }

  object Immutable extends ThriftStructCodec3[GetMembersResponseST] {
    override def encode(_item: GetMembersResponseST, _oproto: TProtocol) { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): GetMembersResponseST = GetMembersResponseST.decode(_iprot)
  }

  /**
   * The default read-only implementation of GetMembersResponseST.  You typically should not need to
   * directly reference this class; instead, use the GetMembersResponseST.apply method to construct
   * new instances.
   */
  class Immutable(
    val success: Boolean,
    val members: Seq[String],
    override val _passthroughFields: immutable$Map[Short, TFieldBlob]
  ) extends GetMembersResponseST {
    def this(
      success: Boolean,
      members: Seq[String] = Seq[String]()
    ) = this(
      success,
      members,
      Map.empty
    )
  }

  /**
   * This Proxy trait allows you to extend the GetMembersResponseST trait with additional state or
   * behavior and implement the read-only methods from GetMembersResponseST using an underlying
   * instance.
   */
  trait Proxy extends GetMembersResponseST {
    protected def _underlying_GetMembersResponseST: GetMembersResponseST
    override def success: Boolean = _underlying_GetMembersResponseST.success
    override def members: Seq[String] = _underlying_GetMembersResponseST.members
    override def _passthroughFields = _underlying_GetMembersResponseST._passthroughFields
  }
}

trait GetMembersResponseST
  extends ThriftStruct
  with scala.Product2[Boolean, Seq[String]]
  with java.io.Serializable
{
  import GetMembersResponseST._

  def success: Boolean
  def members: Seq[String]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = success
  def _2 = members

  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returend.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) orElse {
      val _fieldOpt: Option[TField] =
        _fieldId match {
          case 1 =>
            if (true) {
              writeSuccessValue(success, _oprot)
              Some(GetMembersResponseST.SuccessField)
            } else {
              None
            }
          case 2 =>
            if (members ne null) {
              writeMembersValue(members, _oprot)
              Some(GetMembersResponseST.MembersField)
            } else {
              None
            }
          case _ => None
        }
      _fieldOpt match {
        case Some(_field) =>
          val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
          Some(TFieldBlob(_field, _data))
        case None =>
          None
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): GetMembersResponseST = {
    var success: Boolean = this.success
    var members: Seq[String] = this.members
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        success = readSuccessValue(_blob.read)
      case 2 =>
        members = readMembersValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      success,
      members,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): GetMembersResponseST = {
    var success: Boolean = this.success
    var members: Seq[String] = this.members

    _fieldId match {
      case 1 =>
        success = false
      case 2 =>
        members = Seq[String]()
      case _ =>
    }
    new Immutable(
      success,
      members,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetSuccess: GetMembersResponseST = unsetField(1)

  def unsetMembers: GetMembersResponseST = unsetField(2)


  override def write(_oprot: TProtocol) {
    GetMembersResponseST.validate(this)
    _oprot.writeStructBegin(Struct)
    writeSuccessField(success, _oprot)
    if (members ne null) writeMembersField(members, _oprot)
    _passthroughFields.values foreach { _.write(_oprot) }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    success: Boolean = this.success,
    members: Seq[String] = this.members,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): GetMembersResponseST =
    new Immutable(
      success,
      members,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[GetMembersResponseST]

  override def equals(other: Any): Boolean =
    _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[GetMembersResponseST]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.success
    case 1 => this.members
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "GetMembersResponseST"
}