/**
 * Generated by Scrooge
 *   version: 3.14.1
 *   rev: a996c1128a032845c508102d62e65fc0aa7a5f41
 *   built at: 20140501-114733
 */
package com.am.ds.raft.rpc.thrift

import com.twitter.scrooge.{
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object JoinRequestST extends ThriftStructCodec3[JoinRequestST] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("JoinRequestST")
  val MemberIdField = new TField("memberId", TType.STRING, 1)
  val MemberIdFieldManifest = implicitly[Manifest[String]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      MemberIdField,
      false,
      MemberIdFieldManifest,
      None,
      None,
      immutable$Map(
      ),
      immutable$Map(
      )
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map[String, String](
    )

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: JoinRequestST) {
    if (_item.memberId == null) throw new TProtocolException("Required field memberId cannot be null")
  }

  override def encode(_item: JoinRequestST, _oproto: TProtocol) {
    _item.write(_oproto)
  }

  override def decode(_iprot: TProtocol): JoinRequestST = {
    var memberId: String = null
    var _got_memberId = false
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING => {
                memberId = readMemberIdValue(_iprot)
                _got_memberId = true
              }
              case _actualType =>
                val _expectedType = TType.STRING
            
                throw new TProtocolException(
                  "Received wrong type for field 'memberId' (expected=%s, actual=%s).".format(
                    ttypeToHuman(_expectedType),
                    ttypeToHuman(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_memberId) throw new TProtocolException("Required field 'JoinRequestST' was not found in serialized data for struct JoinRequestST")
    new Immutable(
      memberId,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    memberId: String
  ): JoinRequestST =
    new Immutable(
      memberId
    )

  def unapply(_item: JoinRequestST): Option[String] = Some(_item.memberId)


  private def readMemberIdValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  private def writeMemberIdField(memberId_item: String, _oprot: TProtocol) {
    _oprot.writeFieldBegin(MemberIdField)
    writeMemberIdValue(memberId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeMemberIdValue(memberId_item: String, _oprot: TProtocol) {
    _oprot.writeString(memberId_item)
  }



  private def ttypeToHuman(byte: Byte) = {
    // from https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/protocol/TType.java
    byte match {
      case TType.STOP   => "STOP"
      case TType.VOID   => "VOID"
      case TType.BOOL   => "BOOL"
      case TType.BYTE   => "BYTE"
      case TType.DOUBLE => "DOUBLE"
      case TType.I16    => "I16"
      case TType.I32    => "I32"
      case TType.I64    => "I64"
      case TType.STRING => "STRING"
      case TType.STRUCT => "STRUCT"
      case TType.MAP    => "MAP"
      case TType.SET    => "SET"
      case TType.LIST   => "LIST"
      case TType.ENUM   => "ENUM"
      case _            => "UNKNOWN"
    }
  }

  object Immutable extends ThriftStructCodec3[JoinRequestST] {
    override def encode(_item: JoinRequestST, _oproto: TProtocol) { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): JoinRequestST = JoinRequestST.decode(_iprot)
  }

  /**
   * The default read-only implementation of JoinRequestST.  You typically should not need to
   * directly reference this class; instead, use the JoinRequestST.apply method to construct
   * new instances.
   */
  class Immutable(
    val memberId: String,
    override val _passthroughFields: immutable$Map[Short, TFieldBlob]
  ) extends JoinRequestST {
    def this(
      memberId: String
    ) = this(
      memberId,
      Map.empty
    )
  }

  /**
   * This Proxy trait allows you to extend the JoinRequestST trait with additional state or
   * behavior and implement the read-only methods from JoinRequestST using an underlying
   * instance.
   */
  trait Proxy extends JoinRequestST {
    protected def _underlying_JoinRequestST: JoinRequestST
    override def memberId: String = _underlying_JoinRequestST.memberId
    override def _passthroughFields = _underlying_JoinRequestST._passthroughFields
  }
}

trait JoinRequestST
  extends ThriftStruct
  with scala.Product1[String]
  with java.io.Serializable
{
  import JoinRequestST._

  def memberId: String

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = memberId

  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returend.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) orElse {
      val _fieldOpt: Option[TField] =
        _fieldId match {
          case 1 =>
            if (memberId ne null) {
              writeMemberIdValue(memberId, _oprot)
              Some(JoinRequestST.MemberIdField)
            } else {
              None
            }
          case _ => None
        }
      _fieldOpt match {
        case Some(_field) =>
          val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
          Some(TFieldBlob(_field, _data))
        case None =>
          None
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): JoinRequestST = {
    var memberId: String = this.memberId
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        memberId = readMemberIdValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      memberId,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): JoinRequestST = {
    var memberId: String = this.memberId

    _fieldId match {
      case 1 =>
        memberId = null
      case _ =>
    }
    new Immutable(
      memberId,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetMemberId: JoinRequestST = unsetField(1)


  override def write(_oprot: TProtocol) {
    JoinRequestST.validate(this)
    _oprot.writeStructBegin(Struct)
    if (memberId ne null) writeMemberIdField(memberId, _oprot)
    _passthroughFields.values foreach { _.write(_oprot) }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    memberId: String = this.memberId,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): JoinRequestST =
    new Immutable(
      memberId,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[JoinRequestST]

  override def equals(other: Any): Boolean =
    _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[JoinRequestST]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 1

  override def productElement(n: Int): Any = n match {
    case 0 => this.memberId
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "JoinRequestST"
}