/**
 * Generated by Scrooge
 *   version: 3.14.1
 *   rev: a996c1128a032845c508102d62e65fc0aa7a5f41
 *   built at: 20140501-114733
 */
package com.am.ds.raft.rpc.thrift

import com.twitter.scrooge.{
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object JoinResponseST extends ThriftStructCodec3[JoinResponseST] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("JoinResponseST")
  val SuccessField = new TField("success", TType.BOOL, 1)
  val SuccessFieldManifest = implicitly[Manifest[Boolean]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      SuccessField,
      false,
      SuccessFieldManifest,
      None,
      None,
      immutable$Map(
      ),
      immutable$Map(
      )
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map[String, String](
    )

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: JoinResponseST) {
  }

  override def encode(_item: JoinResponseST, _oproto: TProtocol) {
    _item.write(_oproto)
  }

  override def decode(_iprot: TProtocol): JoinResponseST = {
    var success: Boolean = false
    var _got_success = false
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.BOOL => {
                success = readSuccessValue(_iprot)
                _got_success = true
              }
              case _actualType =>
                val _expectedType = TType.BOOL
            
                throw new TProtocolException(
                  "Received wrong type for field 'success' (expected=%s, actual=%s).".format(
                    ttypeToHuman(_expectedType),
                    ttypeToHuman(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_success) throw new TProtocolException("Required field 'JoinResponseST' was not found in serialized data for struct JoinResponseST")
    new Immutable(
      success,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    success: Boolean
  ): JoinResponseST =
    new Immutable(
      success
    )

  def unapply(_item: JoinResponseST): Option[Boolean] = Some(_item.success)


  private def readSuccessValue(_iprot: TProtocol): Boolean = {
    _iprot.readBool()
  }

  private def writeSuccessField(success_item: Boolean, _oprot: TProtocol) {
    _oprot.writeFieldBegin(SuccessField)
    writeSuccessValue(success_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeSuccessValue(success_item: Boolean, _oprot: TProtocol) {
    _oprot.writeBool(success_item)
  }



  private def ttypeToHuman(byte: Byte) = {
    // from https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/protocol/TType.java
    byte match {
      case TType.STOP   => "STOP"
      case TType.VOID   => "VOID"
      case TType.BOOL   => "BOOL"
      case TType.BYTE   => "BYTE"
      case TType.DOUBLE => "DOUBLE"
      case TType.I16    => "I16"
      case TType.I32    => "I32"
      case TType.I64    => "I64"
      case TType.STRING => "STRING"
      case TType.STRUCT => "STRUCT"
      case TType.MAP    => "MAP"
      case TType.SET    => "SET"
      case TType.LIST   => "LIST"
      case TType.ENUM   => "ENUM"
      case _            => "UNKNOWN"
    }
  }

  object Immutable extends ThriftStructCodec3[JoinResponseST] {
    override def encode(_item: JoinResponseST, _oproto: TProtocol) { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): JoinResponseST = JoinResponseST.decode(_iprot)
  }

  /**
   * The default read-only implementation of JoinResponseST.  You typically should not need to
   * directly reference this class; instead, use the JoinResponseST.apply method to construct
   * new instances.
   */
  class Immutable(
    val success: Boolean,
    override val _passthroughFields: immutable$Map[Short, TFieldBlob]
  ) extends JoinResponseST {
    def this(
      success: Boolean
    ) = this(
      success,
      Map.empty
    )
  }

  /**
   * This Proxy trait allows you to extend the JoinResponseST trait with additional state or
   * behavior and implement the read-only methods from JoinResponseST using an underlying
   * instance.
   */
  trait Proxy extends JoinResponseST {
    protected def _underlying_JoinResponseST: JoinResponseST
    override def success: Boolean = _underlying_JoinResponseST.success
    override def _passthroughFields = _underlying_JoinResponseST._passthroughFields
  }
}

trait JoinResponseST
  extends ThriftStruct
  with scala.Product1[Boolean]
  with java.io.Serializable
{
  import JoinResponseST._

  def success: Boolean

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = success

  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returend.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) orElse {
      val _fieldOpt: Option[TField] =
        _fieldId match {
          case 1 =>
            if (true) {
              writeSuccessValue(success, _oprot)
              Some(JoinResponseST.SuccessField)
            } else {
              None
            }
          case _ => None
        }
      _fieldOpt match {
        case Some(_field) =>
          val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
          Some(TFieldBlob(_field, _data))
        case None =>
          None
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): JoinResponseST = {
    var success: Boolean = this.success
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        success = readSuccessValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      success,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): JoinResponseST = {
    var success: Boolean = this.success

    _fieldId match {
      case 1 =>
        success = false
      case _ =>
    }
    new Immutable(
      success,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetSuccess: JoinResponseST = unsetField(1)


  override def write(_oprot: TProtocol) {
    JoinResponseST.validate(this)
    _oprot.writeStructBegin(Struct)
    writeSuccessField(success, _oprot)
    _passthroughFields.values foreach { _.write(_oprot) }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    success: Boolean = this.success,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): JoinResponseST =
    new Immutable(
      success,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[JoinResponseST]

  override def equals(other: Any): Boolean =
    _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[JoinResponseST]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 1

  override def productElement(n: Int): Any = n match {
    case 0 => this.success
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "JoinResponseST"
}