/**
 * Generated by Scrooge
 *   version: 3.14.1
 *   rev: a996c1128a032845c508102d62e65fc0aa7a5f41
 *   built at: 20140501-114733
 */
package com.am.ds.raft.rpc.thrift

import com.twitter.scrooge.{
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object RequestVoteResponseST extends ThriftStructCodec3[RequestVoteResponseST] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("RequestVoteResponseST")
  val CurrentTermField = new TField("currentTerm", TType.I32, 1)
  val CurrentTermFieldManifest = implicitly[Manifest[Int]]
  val GrantedField = new TField("granted", TType.BOOL, 2)
  val GrantedFieldManifest = implicitly[Manifest[Boolean]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      CurrentTermField,
      false,
      CurrentTermFieldManifest,
      None,
      None,
      immutable$Map(
      ),
      immutable$Map(
      )
    ),
    new ThriftStructFieldInfo(
      GrantedField,
      false,
      GrantedFieldManifest,
      None,
      None,
      immutable$Map(
      ),
      immutable$Map(
      )
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map[String, String](
    )

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: RequestVoteResponseST) {
  }

  override def encode(_item: RequestVoteResponseST, _oproto: TProtocol) {
    _item.write(_oproto)
  }

  override def decode(_iprot: TProtocol): RequestVoteResponseST = {
    var currentTerm: Int = 0
    var _got_currentTerm = false
    var granted: Boolean = false
    var _got_granted = false
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 => {
                currentTerm = readCurrentTermValue(_iprot)
                _got_currentTerm = true
              }
              case _actualType =>
                val _expectedType = TType.I32
            
                throw new TProtocolException(
                  "Received wrong type for field 'currentTerm' (expected=%s, actual=%s).".format(
                    ttypeToHuman(_expectedType),
                    ttypeToHuman(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.BOOL => {
                granted = readGrantedValue(_iprot)
                _got_granted = true
              }
              case _actualType =>
                val _expectedType = TType.BOOL
            
                throw new TProtocolException(
                  "Received wrong type for field 'granted' (expected=%s, actual=%s).".format(
                    ttypeToHuman(_expectedType),
                    ttypeToHuman(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_currentTerm) throw new TProtocolException("Required field 'RequestVoteResponseST' was not found in serialized data for struct RequestVoteResponseST")
    if (!_got_granted) throw new TProtocolException("Required field 'RequestVoteResponseST' was not found in serialized data for struct RequestVoteResponseST")
    new Immutable(
      currentTerm,
      granted,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    currentTerm: Int,
    granted: Boolean
  ): RequestVoteResponseST =
    new Immutable(
      currentTerm,
      granted
    )

  def unapply(_item: RequestVoteResponseST): Option[scala.Product2[Int, Boolean]] = Some(_item)


  private def readCurrentTermValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  private def writeCurrentTermField(currentTerm_item: Int, _oprot: TProtocol) {
    _oprot.writeFieldBegin(CurrentTermField)
    writeCurrentTermValue(currentTerm_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeCurrentTermValue(currentTerm_item: Int, _oprot: TProtocol) {
    _oprot.writeI32(currentTerm_item)
  }

  private def readGrantedValue(_iprot: TProtocol): Boolean = {
    _iprot.readBool()
  }

  private def writeGrantedField(granted_item: Boolean, _oprot: TProtocol) {
    _oprot.writeFieldBegin(GrantedField)
    writeGrantedValue(granted_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeGrantedValue(granted_item: Boolean, _oprot: TProtocol) {
    _oprot.writeBool(granted_item)
  }



  private def ttypeToHuman(byte: Byte) = {
    // from https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/protocol/TType.java
    byte match {
      case TType.STOP   => "STOP"
      case TType.VOID   => "VOID"
      case TType.BOOL   => "BOOL"
      case TType.BYTE   => "BYTE"
      case TType.DOUBLE => "DOUBLE"
      case TType.I16    => "I16"
      case TType.I32    => "I32"
      case TType.I64    => "I64"
      case TType.STRING => "STRING"
      case TType.STRUCT => "STRUCT"
      case TType.MAP    => "MAP"
      case TType.SET    => "SET"
      case TType.LIST   => "LIST"
      case TType.ENUM   => "ENUM"
      case _            => "UNKNOWN"
    }
  }

  object Immutable extends ThriftStructCodec3[RequestVoteResponseST] {
    override def encode(_item: RequestVoteResponseST, _oproto: TProtocol) { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): RequestVoteResponseST = RequestVoteResponseST.decode(_iprot)
  }

  /**
   * The default read-only implementation of RequestVoteResponseST.  You typically should not need to
   * directly reference this class; instead, use the RequestVoteResponseST.apply method to construct
   * new instances.
   */
  class Immutable(
    val currentTerm: Int,
    val granted: Boolean,
    override val _passthroughFields: immutable$Map[Short, TFieldBlob]
  ) extends RequestVoteResponseST {
    def this(
      currentTerm: Int,
      granted: Boolean
    ) = this(
      currentTerm,
      granted,
      Map.empty
    )
  }

  /**
   * This Proxy trait allows you to extend the RequestVoteResponseST trait with additional state or
   * behavior and implement the read-only methods from RequestVoteResponseST using an underlying
   * instance.
   */
  trait Proxy extends RequestVoteResponseST {
    protected def _underlying_RequestVoteResponseST: RequestVoteResponseST
    override def currentTerm: Int = _underlying_RequestVoteResponseST.currentTerm
    override def granted: Boolean = _underlying_RequestVoteResponseST.granted
    override def _passthroughFields = _underlying_RequestVoteResponseST._passthroughFields
  }
}

trait RequestVoteResponseST
  extends ThriftStruct
  with scala.Product2[Int, Boolean]
  with java.io.Serializable
{
  import RequestVoteResponseST._

  def currentTerm: Int
  def granted: Boolean

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = currentTerm
  def _2 = granted

  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returend.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) orElse {
      val _fieldOpt: Option[TField] =
        _fieldId match {
          case 1 =>
            if (true) {
              writeCurrentTermValue(currentTerm, _oprot)
              Some(RequestVoteResponseST.CurrentTermField)
            } else {
              None
            }
          case 2 =>
            if (true) {
              writeGrantedValue(granted, _oprot)
              Some(RequestVoteResponseST.GrantedField)
            } else {
              None
            }
          case _ => None
        }
      _fieldOpt match {
        case Some(_field) =>
          val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
          Some(TFieldBlob(_field, _data))
        case None =>
          None
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): RequestVoteResponseST = {
    var currentTerm: Int = this.currentTerm
    var granted: Boolean = this.granted
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        currentTerm = readCurrentTermValue(_blob.read)
      case 2 =>
        granted = readGrantedValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      currentTerm,
      granted,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): RequestVoteResponseST = {
    var currentTerm: Int = this.currentTerm
    var granted: Boolean = this.granted

    _fieldId match {
      case 1 =>
        currentTerm = 0
      case 2 =>
        granted = false
      case _ =>
    }
    new Immutable(
      currentTerm,
      granted,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetCurrentTerm: RequestVoteResponseST = unsetField(1)

  def unsetGranted: RequestVoteResponseST = unsetField(2)


  override def write(_oprot: TProtocol) {
    RequestVoteResponseST.validate(this)
    _oprot.writeStructBegin(Struct)
    writeCurrentTermField(currentTerm, _oprot)
    writeGrantedField(granted, _oprot)
    _passthroughFields.values foreach { _.write(_oprot) }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    currentTerm: Int = this.currentTerm,
    granted: Boolean = this.granted,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): RequestVoteResponseST =
    new Immutable(
      currentTerm,
      granted,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[RequestVoteResponseST]

  override def equals(other: Any): Boolean =
    _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[RequestVoteResponseST]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.currentTerm
    case 1 => this.granted
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "RequestVoteResponseST"
}